version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: rpg_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpg
      MYSQL_USER: rpg_user
      MYSQL_PASSWORD: rpg_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: rpg_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://rpg_user:rpg_pass@db:3306/rpg
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: rpg_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  db_data:
