"""Preferencias de combate a caballero

Revision ID: 0d165001aae0
Revises: 5cf4bc124a08
Create Date: 2025-10-20 23:53:49.355077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d165001aae0'
down_revision: Union[str, Sequence[str], None] = '5cf4bc124a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Caballero', sa.Column('ca_msg_win', sa.String(length=200), nullable=True))
    op.add_column('Caballero', sa.Column('ca_msg_loss', sa.String(length=200), nullable=True))
    op.add_column('Caballero', sa.Column('ca_img_main', sa.String(length=5000), nullable=True))
    op.add_column('Caballero', sa.Column('ca_img_win', sa.String(length=5000), nullable=True))
    op.add_column('Caballero', sa.Column('ca_img_loss', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Caballero', 'ca_img_loss')
    op.drop_column('Caballero', 'ca_img_win')
    op.drop_column('Caballero', 'ca_img_main')
    op.drop_column('Caballero', 'ca_msg_loss')
    op.drop_column('Caballero', 'ca_msg_win')
    # ### end Alembic commands ###
