"""Columna de cantidad agregada a la tabla Boost

Revision ID: 4de9acf1fab7
Revises: a97c4e24e429
Create Date: 2025-09-13 23:58:34.834965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de9acf1fab7'
down_revision: Union[str, Sequence[str], None] = 'a97c4e24e429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Boost', sa.Column('bo_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Boost', 'bo_quantity')
    # ### end Alembic commands ###
