"""Cambios en tabla de combate, se agregan columnas para npc, quest, background y se elimina la llave de defensor para que pueda ser o pj o npc

Revision ID: 5cf4bc124a08
Revises: b7e4e64df1a8
Create Date: 2025-10-08 03:33:39.278528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf4bc124a08'
down_revision: Union[str, Sequence[str], None] = 'b7e4e64df1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Combate', sa.Column('battle_type', sa.String(length=30), nullable=True))
    op.add_column('Combate', sa.Column('battle_quest_id', sa.Integer(), nullable=True))
    op.add_column('Combate', sa.Column('battle_npc_id', sa.BigInteger(), nullable=True))
    op.add_column('Combate', sa.Column('battle_background', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('Combate_ibfk_2'), 'Combate', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('Combate_ibfk_2'), 'Combate', 'Caballero', ['co_ca_key_defender'], ['ca_key'])
    op.drop_column('Combate', 'battle_background')
    op.drop_column('Combate', 'battle_npc_id')
    op.drop_column('Combate', 'battle_quest_id')
    op.drop_column('Combate', 'battle_type')
    # ### end Alembic commands ###
