"""250911_Migracion_inicial

Revision ID: 83163dd472f9
Revises: 
Create Date: 2025-09-11 21:55:22.878354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83163dd472f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Caballero', sa.Column('ca_di_key', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_zo_key', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_zon_key_act', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_lastaction', sa.DateTime(), nullable=True))
    op.add_column('Caballero', sa.Column('ca_status_player', sa.Boolean(), nullable=False))
    op.alter_column('Caballero', 'ca_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'Caballero', 'Zodiaco', ['ca_zo_key'], ['zo_key'])
    op.create_foreign_key(None, 'Caballero', 'Divinidad', ['ca_di_key'], ['di_key'])
    op.create_foreign_key(None, 'Caballero', 'Zonas', ['ca_zon_key_act'], ['zon_key'])
    op.add_column('Zonas', sa.Column('zon_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Zonas', 'zon_image')
    op.drop_constraint(None, 'Caballero', type_='foreignkey')
    op.drop_constraint(None, 'Caballero', type_='foreignkey')
    op.drop_constraint(None, 'Caballero', type_='foreignkey')
    op.alter_column('Caballero', 'ca_status',
               existing_type=sa.String(length=30),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('Caballero', 'ca_status_player')
    op.drop_column('Caballero', 'ca_lastaction')
    op.drop_column('Caballero', 'ca_zon_key_act')
    op.drop_column('Caballero', 'ca_zo_key')
    op.drop_column('Caballero', 'ca_di_key')
    # ### end Alembic commands ###
