"""Nuevos campos a tabla de Caballero

Revision ID: a97c4e24e429
Revises: b119a52c0cc5
Create Date: 2025-09-12 02:09:27.455109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97c4e24e429'
down_revision: Union[str, Sequence[str], None] = 'b119a52c0cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Caballero', sa.Column('ca_hability', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_health_act', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_cosmo_act', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_seventh_sense_act', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_honor', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_win', sa.Integer(), nullable=False))
    op.add_column('Caballero', sa.Column('ca_loss', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Caballero', 'ca_loss')
    op.drop_column('Caballero', 'ca_win')
    op.drop_column('Caballero', 'ca_honor')
    op.drop_column('Caballero', 'ca_seventh_sense_act')
    op.drop_column('Caballero', 'ca_cosmo_act')
    op.drop_column('Caballero', 'ca_health_act')
    op.drop_column('Caballero', 'ca_hability')
    # ### end Alembic commands ###
